
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xbe\x08_V^\xc5\xacc@p\x96j*\x18\x08\xfc'
    
_lr_action_items = {'NAME':([1,3,5,6,7,8,9,10,11,12,13,14,15,17,],[3,-4,-6,3,-10,-14,-11,-5,-7,-13,-9,-12,-1,-8,]),'INT':([3,7,8,9,11,12,13,14,],[7,-10,-14,-11,7,-13,-9,-12,]),'SYMBOL':([3,7,8,9,11,12,13,14,],[8,-10,-14,-11,8,-13,-9,-12,]),'FLOAT':([3,7,8,9,11,12,13,14,],[9,-10,-14,-11,9,-13,-9,-12,]),'UUID':([3,7,8,9,11,12,13,14,],[12,-10,-14,-11,12,-13,-9,-12,]),'CLOSE':([3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,],[-4,15,-6,-2,-10,-14,-11,-5,-7,-13,-9,-12,-1,-3,-8,]),'STRING':([3,7,8,9,11,12,13,14,],[14,-10,-14,-11,14,-13,-9,-12,]),'NULL':([3,7,8,9,11,12,13,14,],[13,-10,-14,-11,13,-13,-9,-12,]),'OPEN':([0,1,3,5,6,7,8,9,10,11,12,13,14,15,17,],[1,1,-4,-6,1,-10,-14,-11,-5,-7,-13,-9,-12,-1,-8,]),'$end':([2,15,],[0,-1,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'items':([1,6,],[4,16,]),'list':([3,11,],[10,17,]),'tree':([0,1,6,],[2,5,5,]),'value':([3,11,],[11,11,]),'item':([1,6,],[6,6,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tree","S'",1,None,None,None),
  ('tree -> OPEN items CLOSE','tree',3,'p_tree','rpp.py',84),
  ('items -> item','items',1,'p_items','rpp.py',88),
  ('items -> item items','items',2,'p_items','rpp.py',89),
  ('item -> NAME','item',1,'p_item_novalue','rpp.py',97),
  ('item -> NAME list','item',2,'p_item_list','rpp.py',101),
  ('item -> tree','item',1,'p_item_tree','rpp.py',105),
  ('list -> value','list',1,'p_list','rpp.py',109),
  ('list -> value list','list',2,'p_list','rpp.py',110),
  ('value -> NULL','value',1,'p_value','rpp.py',118),
  ('value -> INT','value',1,'p_value','rpp.py',119),
  ('value -> FLOAT','value',1,'p_value','rpp.py',120),
  ('value -> STRING','value',1,'p_value','rpp.py',121),
  ('value -> UUID','value',1,'p_value','rpp.py',122),
  ('value -> SYMBOL','value',1,'p_value','rpp.py',123),
]
